### ISSUE TITLE
Update configuration in README

### ISSUE THREAD

**Issue by DSIW** [wildbit/postmark-rails#46]
I'm using Rails 3.2 and postmark-rails 0.4.2.

The configuration in your README is:

```ruby
config.action_mailer.delivery_method = :postmark
config.action_mailer.postmark_settings = { :api_token => "your-api-token" }
```

But I had to use:

```ruby
config.action_mailer.delivery_method = :postmark
ActionMailer::Base.postmark_settings = { :api_key => "your-api-token" }
```

**Comment by temochka** [comment]
Hi,

Sorry for your time. The README is for the latest gem version. It supports both `:api_key` and `:api_token`, the latter is recommended because it’s consistent with documentation and user interface. Please refer to the [README for postmark-rails 0.4.2](https://github.com/wildbit/postmark-rails/blob/v0.4.2/README.rdoc) if you wish to use the older version.
