### ISSUE TITLE
Any examples of using this gem w/ new templates features of Postmark? 

### ISSUE THREAD

**Issue by twanlass** [wildbit/postmark-rails#53]

**Comment by temochka** [comment]
Hi @twanlass. Unfortunately the idea of storing templates remotely contradicts the design of ActionMailer. Because of that, if you want to use Postmark templates in a Rails app, then you’ll probably want to give up on ActionMailer. And if you decide to do so, the underlying postmark gem has examples of [sending templated emails](https://github.com/wildbit/postmark-gem#sending-a-templated-email), as well as a [wiki page](https://github.com/wildbit/postmark-gem/wiki/The-Templates-API-support) dedicated to templates management via the API.

I’m going to leave this issue open, as we might want to bundle a re-usable abstraction layer with the rails gem, that would simplify the following aspects of integration:

* **Creating new instances of `Postmark::ApiClient`.** Currently you’ll have to use a shared global instance, introduce a global factory class, or create the client instances in place when needed.
* **Offline development.** In development and test, you’ll probably want to bypass actual sending.
* **Logging.** Some debug output in the logs including template arguments would be very helpful. Especially, in development.
* **Testing.** Possibly we could bundle some test helpers to match the template arguments.

Thanks for bringing this up!

**Comment by twanlass** [comment]
@temochka thanks for the reply. Yea, I assumed this was the case though thought I would I would ask in case I could have both templated emails in ActionMailer along w/ those remotely stored. I'll move forward though w/ creating a shared global instance for now. 

Cheers!

**Comment by SeriouslyAwesome** [comment]
@temochka I was inspired by your comment and decided to put together [a gem](https://github.com/scienceexchange/postmark_mailer) that is essentially a light-weight wrapper around `Postmark::ApiClient#deliver_with_template` that adopts the same interface as ActionMailer. All you have to do is inherit your mailer from `PostmarkMailer::Base` instead of `ActionMailer::Base`, and then update the options you pass into `#mail` to those you would use with the Postmark API client. Example:

```ruby
class MyCoolMailer < PostmarkMailer::Base
  def some_email(user)
    mail(
      to: user.email, 
      from: 'foo@bar.com', 
      template_id: 123456, 
      template_model: { first_name: user.first_name, last_name: user.last_name }
    )
  end
end
```

This can be called in your app just as you would with ActionMailer:

```ruby
MyCoolMailer.some_email(user).deliver_later
```

**WARNING:** I literally just put this together today, so there is minimal documentation and no tests yet (at the time of this comment), so use at your own risk. But for the most simple use cases, it's working, so hopefully it helps some other folks in this situation.

See: [postmark_mailer](https://github.com/scienceexchange/postmark_mailer)

**Comment by temochka** [comment]
Hey @SeriouslyAwesome,

This is... seriously awesome! 😄  We’d like to add something similar to postmark-rails, but it needs to have a good story for test and development environments (as I’d outlined above). If you want to take a stab at a pull request, I’ll be happy to review. Otherwise, we’ll get to it eventually :)

If you’d prefer to keep it as a standalone gem, it’s ok too. We can feature it in the [community libraries](https://postmarkapp.com/developer/integration/community-libraries) section of our developer docs. It’d still be nice if you could first add some tests and offline development mode.

Thank you for your work!

**Comment by SeriouslyAwesome** [comment]
@temochka makes perfect sense. I've been distracted by another project, but maybe I'll see if I can develop this a little more on this standalone repo until it makes sense to port into a PR for `postmark-rails`. Glad to hear it's of interest though!

**Comment by oyeanuj** [comment]
@SeriouslyAwesome Just checking in to see if the plan is still to keep it stand-alone or merge it with this gem?

@temochka Either way, some information about using Rails and template on the site linking to this library would be super helpful!

Thank you for making this possible!

**Comment by dikond** [comment]
Are there are any news on that matter?
And thanks for what you do 🙇

**Comment by temochka** [comment]
Seems like there’s quite a bit of interest in this. Unfortunately, no major Ruby gem updates are currently on the roadmap. We have some templates improvements scheduled down the road which might present a good opportunity to build a better integration, too. Stay tuned.

That said, I’ll share a glimpse of our internal thinking. The Postmark web app is built on Rails too, and the possibility of switching from ActionMailer to Postmark templates has come up quite a few times. Usually the arguments in favor of switching bring up the ability for everyone on the team to edit copy and HTML templates and smaller HTTP payloads. Also people want to have access to built-in templates 😄 These are all good reasons, but there is also a number of other concerns:

* The experience of managing several different versions of templates across multiple Postmark servers (e.g., staging, production) is far from perfect. This just got a little more manageable with support for template aliases, but some non-trivial scripting is still required.
* If you run atomic deploys (Capistrano), you’d want to adopt a convention when you never change existing templates and only add new ones by duplicating the old ones. The alternative is built-in versioning support on Postmark end with ability to link to specific versions.
* You also need some conventions if you have multiple developers working on the app or you keep multiple active Git branches at a time. You don’t want to face "merge conflicts" or accidentally overwrite someone’s changes.
* Currently no support for partials (this will definitely be fixed).
* Last but not least, you lose the ability to test email bodies with Rails (at least offline).

Don’t get me wrong, we actively use templates for smaller apps and services, but with Rails it’s very hard to compete with ActionMailer paired with Postmark adapters. I’d appreciate some feedback from the community on how you’d address the issues above and if they even present a problem to your app. Thanks!

**Comment by oyeanuj** [comment]
@temochka In my experience, templates have been invaluable to work with when working in a small team or non-tech team members. It saves the pain of porting from Rails to templates or the other way around just to finalize on email templates.

I think a lot of the problems that you have mentioned are very valid for bigger teams but less so for the smaller ones. At the very least, you could have experimental support for templates using ActionMailer where in it is made clear that the workflow isn't ideal but just the first step in this process.

**Comment by dikond** [comment]
We're just starting to use templates so I can't provide much feedback, but we really value an ability to edit html/text for a non-developers which saves a lot of time ❤️ 

My primary concern is testing. What would really help is a feature to forward outbound emails or at least have some kind of _sandbox_ mode to not send emails to the real users. Forwarding emails to SMTP server would allow us to use tools like [mailtrap](https://mailtrap.io/).

**Comment by litodertechie** [comment]
Any news on that matter ? 💃

**Comment by litodertechie** [comment]
Btw I just tried the PostmarkMailer gem from @SeriouslyAwesome and it works really well !!

**Comment by SeriouslyAwesome** [comment]
Just wanted to drop a quick follow-up note here that I've published `postmark_mailer` on [Rubygems.org](https://rubygems.org/gems/postmark_mailer) so you can now include the gem without referencing the Github repo: `gem 'postmark_mailer'`. I've only added a few new things as needed for our use of the gem at work, so no major improvements in test coverage and other normally ideal things a good gem should have, but I may find some time to polish this up a bit more in my personal free time soon.

**Comment by we5** [comment]
Also going to test out the gem from @SeriouslyAwesome. I currently evaluate Sendgrid and Postmark and while Sendgrid does provide a way to use their templates, their customisation is not 100% perfect for localised templates because the preheader is not taking the Handlebar syntax into account. 

I definitely think there is a reasonable space for providing templates via Postmark/Sendgrid to  ActionMailer, because sometimes its necessary to edit/version/tryout templates independently from deployments. Also if you have API-only endpoints and don't want to bother with static assets, the use of such services is handy.

**Comment by damien-roche** [comment]
In the vain of magic in Rails I expected `template_alias` or `template_id` and `template_model` to Just Work in the mailer, as I expect many other Rails' devs would.

**Comment by temochka** [comment]
The `postmark-rails` gem version `0.19` (available very soon) and above will support sending templated emails via ActionMailer. This way you keep access to all the goodies ActionMailer has to offer: interceptors, test matchers, development logging, previews, delayed delivery, etc., but anyone on your team can make edits to email content and there’s no need to redeploy the app if you’re only changing the copy. You can find out more in the [new guide on the Wiki](https://github.com/wildbit/postmark-rails/wiki/Using-Postmark-Templates).

**Comment by oyeanuj** [comment]
@temochka That's great news! How does it compare to the `postmark-mailer` in terms of functionality?

**Comment by temochka** [comment]
I think `postmark-mailer` is a good lightweight alternative. There’s no need to switch if you’re using it and it works. However, the migration path is relatively straightforward:

1. Change the base class
2. Edit arguments to `#mail` to comply with ActionMailer.

I wanted to stick with ActionMailer to stay closer to Rails so we could present a more familiar story for development and testing. Templated mailers work just as regular mailers, but no templates.

Aside from familiar ActionMailer perks and the preview interceptor, we also plan to add a Capistrano plugin for deploying templates using the newly introduced [Templates Push API](https://postmarkapp.com/developer/api/templates-api#push-templates) some time in the near future.

**Comment by dogweather** [comment]
Could someone connect the last dot for me ... how would I hook this in to a vanilla Rails + Devise app? That's my scenario, and I bet it's super-common: wouldn't most Rails developers be using Devise to generate their transactional mail?

**Comment by damien-roche** [comment]
Fully endorse the above. 

If Devise starts getting in the way, you need to untangle it from your views, routes, controllers and mailers. Inherit from Devise base classes and write custom actions if you need to, same for custom mailers, templates. Wrap up your authentication to maintain a consistent interface and simply use that to talk to Devise.

Much much simpler and it puts you back in control of how your user authentication interacts with the rest of your application. Devise should integrate into your application, not the other way around.

**Comment by dogweather** [comment]
Thanks! I can see for my simple app's use case, the open source templates will be enough --- and then sending through Postmark which will inline the CSS.
